services:
  nodeaplication:
    container_name: nodeaplication-test-gustavo
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - 3000:3000

    volumes:
      - ./:/app
    command: >
      bash -c '
        yarn dev
      '
      
volumes:
  data-nodeaplication: